load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

define_mgk_ko(
    name = "emi-mpu",
    outs = [
        "emi_legacy/emi-dummy.ko",
        "emi_legacy/emi_legacy_v1/emicen.ko",
        "emi_legacy/emi_legacy_v1/emictrl.ko",
        "emi_legacy/emi_legacy_v1/emiisu.ko",
        "emi_legacy/emi_legacy_v1/emimpu.ko",
        "mtk_dramc.ko",
    ],
)
