load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
    "gz-trusty/Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

define_mgk_ko(
    name = "geniezone",
    outs = [
        "gz_main_mod.ko",
        "gz-trusty/gz_ipc_mod.ko",
        "gz-trusty/gz_irq_mod.ko",
        "gz-trusty/gz_log_mod.ko",
        "gz-trusty/gz_trusty_mod.ko",
        "gz-trusty/gz_virtio_mod.ko",
        "gz_tz_system.ko",
    ],
)
