ifneq ($(filter y m,$(CONFIG_OEM_LAMU_FINGERPRINT) $(CONFIG_OEM_FIRE_FINGERPRINT)),)
	FP_OBJS += gf_spi_tee.o
endif

obj-$(CONFIG_OEM_LAMU_FINGERPRINT) += gf_tee.o
obj-$(CONFIG_OEM_FIRE_FINGERPRINT) += gf_tee.o
gf_tee-y := $(FP_OBJS)
