load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

ddk_headers(
    name = "gpu_utility_headers",
    hdrs = glob([
        "**/*.h",
    ]),
    includes = [
        ".",
    ],
)
