load("//build/bazel_mgk_rules:mgk_ko.bzl", "define_mgk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

exports_files([
    "Kconfig",
])

filegroup(
    name = "sources",
    srcs = glob([
        "**",
    ], exclude = [
        "BUILD.bazel",
    ]),
)

define_mgk_ko(
    name = "mtk-mml",
    deps = [
        "//kernel_device_modules-6.6/drivers/misc/mediatek/aee/aed:aee_aed",
        "//kernel_device_modules-6.6/drivers/misc/mediatek/cmdq/mailbox:mtk-cmdq-drv-ext",
        "//kernel_device_modules-6.6/drivers/misc/mediatek/mme/src:mme",
        "//kernel_device_modules-6.6/drivers/misc/mediatek/mmp/src:mmprofile",
        "//kernel_device_modules-6.6/drivers/misc/mediatek/mtk-interconnect:mtk-icc-core",
    ],
    outs = [
        "mtk-mml.ko",
    ],
)
